// js/playlist.js
import { generatePlaylist } from "../logic/generator.js";
import { createMoodTunesPlaylist } from "../logic/createPlaylist.js";
import { isAuthenticated } from "../spotify/spotify.auth.js";
import { spotify } from "../spotify/spotify.adapter.js";

const playlistNameEl = document.getElementById("playlist-name");
const tracksEl = document.getElementById("tracks");
const createBtn = document.getElementById("create-btn");
const customizeBtn = document.getElementById("customize-btn");
const createdEl = document.getElementById("created");
const userInfo = document.getElementById("user-info");

const OPTIONS_KEY = "playlistOptions";
const FINAL_LIMIT = 15; // ✅ always 15

let currentPlaylist = null;

function setStatus(msg) {
  if (createdEl) createdEl.textContent = msg || "";
}

async function showUserInfo() {
  if (!userInfo) return;

  if (!isAuthenticated()) {
    userInfo.textContent = "Not logged in";
    return;
  }

  try {
    const user = await spotify.getMe();
    userInfo.textContent = `Logged in as: ${user.display_name || user.id}`;
  } catch (err) {
    console.error(err);
    userInfo.textContent = "Logged in";
  }
}

function renderTracks(tracks = []) {
  if (!tracksEl) return;
  tracksEl.innerHTML = "";

  if (!Array.isArray(tracks) || tracks.length === 0) {
    const li = document.createElement("li");
    li.textContent = "No tracks found.";
    tracksEl.appendChild(li);
    return;
  }

  tracks.forEach((t, i) => {
    const li = document.createElement("li");
    const title = t?.name || "Unknown title";

    // accept both: artists string OR array
    let artists = "";
    if (Array.isArray(t?.artists)) {
      artists = t.artists.map((a) => (typeof a === "string" ? a : a?.name)).filter(Boolean).join(", ");
    } else if (typeof t?.artists === "string") {
      artists = t.artists;
    } else if (typeof t?.artist === "string") {
      artists = t.artist;
    }

    li.textContent = `${i + 1}. ${title}${artists ? " — " + artists : ""}`;
    tracksEl.appendChild(li);
  });
}

function getOptions() {
  const raw = localStorage.getItem(OPTIONS_KEY);
  if (!raw) return null;

  try {
    const obj = JSON.parse(raw);
    return {
      mood: obj?.mood || "neutral",
      intent: obj?.intent || "go-with-flow",
      // ✅ force 15 always
      limit: FINAL_LIMIT,
    };
  } catch (e) {
    console.error("Failed to parse playlistOptions:", e);
    return null;
  }
}

async function loadAndGeneratePlaylist() {
  try {
    const opts = getOptions();
    if (!opts) {
      window.location.assign("./mood-options.html");
      return;
    }

    setStatus(isAuthenticated() ? "Generating playlist..." : "Not logged in — generating preview...");

    const playlist = await generatePlaylist(opts);
    currentPlaylist = playlist || null;

    const tracks = currentPlaylist?.tracks || [];

    if (!tracks.length) {
      playlistNameEl.textContent = "No playlist generated";
      renderTracks([]);
      if (createBtn) createBtn.disabled = true;
      setStatus(isAuthenticated() ? "No tracks returned. Try another mood/intent." : "Login required for Spotify tracks.");
      return;
    }

    // UI title
    playlistNameEl.textContent = `${currentPlaylist.name || "Playlist"} — ${tracks.length} tracks`;
    renderTracks(tracks);

    // Create button logic
    const hasUris = tracks.some((t) => Boolean(t?.uri));
    const canCreate = isAuthenticated() && hasUris;

    if (createBtn) createBtn.disabled = !canCreate;
    setStatus(canCreate ? "Ready to add to Spotify ✅" : "Login required to add to Spotify.");
  } catch (err) {
    console.error("Error generating playlist:", err);
    playlistNameEl.textContent = "Error generating playlist";
    renderTracks([]);
    if (createBtn) createBtn.disabled = true;
    setStatus(`❌ ${err?.message || String(err)}`);
  }
}

async function handleCreate() {
  if (!currentPlaylist?.tracks?.length) return;

  if (!isAuthenticated()) {
    setStatus("Please login to add to Spotify.");
    return;
  }

  const trackUris = currentPlaylist.tracks.map((t) => t?.uri).filter(Boolean);
  if (trackUris.length === 0) {
    setStatus("❌ Tracks missing URIs (cannot add to Spotify).");
    return;
  }

  createBtn.disabled = true;
  setStatus("Creating playlist in Spotify...");

  try {
    const res = await createMoodTunesPlaylist({
      name: currentPlaylist.name || "MoodTunes Playlist",
      description: currentPlaylist.description || "Generated by MoodTunes",
      trackUris,
    });

    const created = res?.playlist || res;
    const url = created?.external_urls?.spotify || "";

    if (createdEl) {
      createdEl.innerHTML = `✅ Created! ${
        url ? `<a href="${url}" target="_blank" rel="noreferrer">Open in Spotify</a>` : ""
      }`;
    }
  } catch (err) {
    console.error(err);
    setStatus(`❌ Failed to create playlist: ${err?.message || String(err)}`);
  } finally {
    createBtn.disabled = false;
  }
}

// Events
createBtn?.addEventListener("click", handleCreate);

customizeBtn?.addEventListener("click", () => {
  window.location.assign("./mood-options.html");
});

// Init
(async function init() {
  await showUserInfo();
  await loadAndGeneratePlaylist();
})();
